<!-- Lesson 4 Task 1: Create a component where each button click stores the current 
    click time in an array and displays that array on the screen. -->
<template>
  <div class="timestamp-component">
    <button @click="saveCurrentTime" class="timestamp-button">Save time</button>

    <ul class="timestamp-list">
      <time-list-item
        v-for="timestamp in timestamps"
        :timestamp="timestamp.datetime"
        :style="timestamp.style"
      />
    </ul>
  </div>
</template>

<script>
import TimeListItem from "./TimeListItem.vue";
export default {
  data() {
    return {
      timestamps: [],
    };
  },
  components: {
    TimeListItem,
  },
  methods: {
    saveCurrentTime() {
      const currentdate = new Date();
      const datetime =
        currentdate.getDate() +
        "/" +
        (currentdate.getMonth() + 1) +
        "/" +
        currentdate.getFullYear() +
        " " +
        currentdate.getHours() +
        ":" +
        currentdate.getMinutes() +
        ":" +
        currentdate.getSeconds();

      const style = this.generateRandomStyle();
      this.timestamps.push({ datetime, style });
    },
    /**
     * Lesson 4 Task 4: Create a dynamic list of elements where each element has a random 
     * background color and font size generated by the component's create method.
     */
    generateRandomStyle() {
      const randomColor = this.getRandomColor();
      const randomFontSize = this.getRandomFontSize();

      const style = {
        backgroundColor: randomColor,
        fontSize: `${randomFontSize}px`,
      };

      return style;
    },
    getRandomColor() {
      const hexLetters = "0123456789ABCDEF";
      let color = "#";

      for (let i = 0; i < 6; i++) {
        color += hexLetters[Math.floor(Math.random() * 16)];
      }
      
      return color;
    },
    getRandomFontSize() {
      return Math.floor(Math.random() * 20) + 12; //font from 12 to 31
    },
  },
};
</script>
